name: Build server branch

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: Create local changes
      run: |
        git checkout -b server
        ./build_server.sh
    - name: Commit files
      run: |
        git config --local user.email "33930674+garywei944@users.noreply.github.com"
        git config --local user.name "garywei944"
        git commit -m "Build the server version with GitHub Actions" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
